library:
  source-dirs: src
tests:
  aoc19-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc19
copyright: 2019 Author name here
maintainer: example@example.com
ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -fno-warn-orphans
- -fwarn-unused-imports
- -fwarn-unused-binds
- -isrc
- -Widentities
dependencies:
- vector
- ilist
- split
- safe
- hspec
- transformers
- parsec
- base >= 4.7 && < 5
name: aoc19
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/aoc19
license: BSD3
executables:
  aoc19-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc19
description: Please see the README on GitHub at <https://github.com/githubuser/aoc19#readme>
